name: Format JavaScript and Vue SFC code

on:
  push:
    paths:
      - '**.js'
      - '**.vue'
      - 'package.json'
      - 'package-lock.json'
      - '.prettierrc.js'
      - '.prettierrc.json'

jobs:
  js-code-formatting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install npm dependencies
        run: npm install

      - name: Run format script
        run: npm run format

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply code formatting for js and vue files
